In [1]:
def abc():
    print('hi')


In [2]:
abc()

hi


In [3]:
k = abc

In [4]:
abc

<function __main__.abc()>

In [5]:
k

<function __main__.abc()>

In [6]:
k()

hi


In [8]:
def xyz(f):
    f()

In [9]:
xyz(k)

hi


In [10]:
xyz(f = abc)

hi


In [11]:
def pqr():
    def qrp():
        print('hello')
    qrp()
pqr

<function __main__.pqr()>

In [18]:
def pqr():
    def qrp():
        print('hello')
    return qrp


In [19]:
x = pqr()
x

<function __main__.pqr.<locals>.qrp()>

In [21]:
x()

hello


In [ ]:
# Python function can be 
# 1. Assigned as a value
# 2. Taken as input argument in another function
# 3. Defined inside another function
# 4.Return a function as output from nother function

In [ ]:
# Annonymous Function - Lambda Expressions
# Lambda inp_arg : output (returned)

# its always one-liner
# always returns
# Input arguments can be multiple,optional,keyword,named etc.
# Output can be simple /conditionals /comprehension  etc.

In [22]:
def doubler(x):
    return x * 2

m = doubler (34)
print(m)
  

68


In [23]:
doubler_L = lambda x : x * 2
doubler_L

<function __main__.<lambda>(x)>

In [24]:
doubler_L(34)

68

In [25]:
oddeve = lambda x: 'Odd' if x%2 else 'Even'
oddeve(45)

'Odd'

In [ ]:

#def alag1()
#  pass
#def alag2()
#  pass
#def alag3()
#  pass


def bada_function():
    step1
    step2
    ..



    f(step)


In [26]:
k = lambda x,y : x*y 
k(3,4)

12

In [27]:
k = lambda : print('hi')
k1 = k()

hi


In [28]:
m = k()
print(m)


hi
None


In [31]:
# Scope of variables
## global 
## local
## nonlocal

In [32]:
x = 10
 
def abc():
    print(x)
 

In [33]:
x = 10

def abc():
    x = 30
    # print(x)


print(x)
abc()
print(x)

10
10


In [41]:
x = 10

def abc():
    global x
    x= 30

print(x)
abc()
print(x)

10
30


In [39]:
x= 10

def abc():
    # global x
    x = 30
    y = 15
    def xyz():
        y = 20
        print('From xyz',x)
    xyz()
    print(y)


print(x)
abc()
print(x)

10
From xyz 30
15
10


In [38]:
x= 10

def abc():
    # global x
    x = 30
    y = 15
    def xyz():
        nonlocal y 
        y = 28
        print('From xyz',x)
    xyz()
    print(y)


print(x)
abc()
print(x)


10
From xyz 30
28
10


In [1]:
# working with python modules
 

In [5]:
import numpy

In [6]:
import my_file

In [7]:
my_file.abc()

Good Message


In [8]:
import keyword

In [9]:
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [10]:
import keyword as kw
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [11]:
from keyword import kwlist
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [12]:
from keyword import kwlist, iskeyword as isk
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [13]:
isk('if')

True

In [14]:
import numpy as np

In [15]:
a = np.array([])
a

array([], dtype=float64)

In [16]:
b = np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [18]:
len(a), len(b)

(0, 5)

In [19]:
a.dtype

dtype('float64')

In [20]:
b.dtype

dtype('int32')

In [21]:
b.size

5

In [22]:
a.shape

(0,)

In [23]:
a.ndim

1

In [24]:
b.ndim

1

In [25]:
type(a)

numpy.ndarray

In [27]:
c = np.array([[2,3,4],[4,5,6],[7,8,9],[10,11,9]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  9]])

In [28]:
c.shape

(4, 3)

In [30]:
d = np.array([[[2,3,4]],[[4,5,6]],[[7,8,9]],[[10,11,9]]])
d

array([[[ 2,  3,  4]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11,  9]]])

In [31]:
d.shape

(4, 1, 3)

In [ ]:
e = np.array([[[2,20],[3,30],[4,40,]],[[7,8,9]],[[10,11,9]]])

In [32]:
c.sum(axis=1)

array([ 9, 15, 24, 30])

In [34]:
c.mean(axis=1)

array([ 3.,  5.,  8., 10.])

In [35]:
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11,  9]])

In [36]:
c[0][1]

3

In [37]:
c[0:2,-1]

array([4, 6])

In [38]:
c[0:2,-1:]

array([[4],
       [6]])