In [1]:
import numpy as np

In [2]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.zeros([2,3],dtype = int )

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.linspace(1,10,10,dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
list(range(1,11,1)) ### range is for only integers

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
np.random.randint(1,6,1)

array([1])

In [9]:
np.random.randint(1,6,1)

array([4])

In [10]:
np.random.randint(1,6,[4,3,2])

array([[[1, 4],
        [2, 4],
        [2, 3]],

       [[5, 5],
        [4, 5],
        [3, 5]],

       [[5, 1],
        [2, 3],
        [5, 5]],

       [[5, 5],
        [2, 4],
        [4, 3]]])

In [11]:
np.random.randint(31,6000,[4,3])

array([[ 933, 1115, 4073],
       [1731, 5229, 4080],
       [4505, 2452, 5529],
       [2179, 2018, 2273]])

In [13]:
np.random.randint(31,6000,[4,3])

array([[1210, 5202, 3333],
       [1573, 3095,  406],
       [1718, 2843,  764],
       [2706, 2516,  499]])

In [15]:
np.random.seed(10)
np.random.randint(31,6000,[4,3])

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [16]:
np.random.seed(54)
np.random.randint(31,6000,[4,3])

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [17]:
np.random.rand(3,4)

array([[0.6714843 , 0.02965701, 0.39156203, 0.40479404],
       [0.18963101, 0.76710564, 0.61672315, 0.92627396],
       [0.32512403, 0.25315435, 0.72021792, 0.99695746]])

In [21]:
r = np.loadtxt('somedata.txt')
r

array([[ 34.,  45.,  67.,  89.],
       [ 23.,  45., 678.,  89.]])

In [20]:
r = np.loadtxt('moredata.txt')
r

array([[45., 54., 67., 78.],
       [45., 67., 89., 90.]])

In [26]:
r= np.loadtxt('redata.txt',dtype= str)
r

array(['hi', 'this', 'is', 'a', 'file', 'outside', 'python'], dtype='<U7')

In [22]:
p = np.random.rand(3,4)
p

array([[0.30787317, 0.17198668, 0.17538453, 0.16382659],
       [0.58501438, 0.47353556, 0.46075695, 0.23515401],
       [0.85621717, 0.47089378, 0.05458343, 0.99325708]])

In [27]:
np.savetxt('new.txt',p,delimiter = ',')

In [ ]:
np.