In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
np.arange(9).reshape(3,3,)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.03136846])

In [11]:
np.random.randn(25)

array([-0.49843058, -0.02705215,  0.42652734, -0.66172051, -1.04784115,
        0.70483402, -0.82621055,  2.25100189,  2.17873812,  0.0556133 ,
        1.33656003, -0.08426726,  0.18414288, -0.72546664,  0.56971454,
       -0.97894859, -1.07754627, -0.13884498, -1.04670877, -1.51048952,
        0.47275329,  0.13309222, -0.89544021, -0.49856744,  0.30750313])

In [12]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [2]:
import numpy as np

In [3]:
np.arange(0.01,1.01,0.01).reshape(10,10).sum(axis=0)

array([4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [4]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
np.arange(12,26)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [7]:
np.random.rand(20)

array([0.7832825 , 0.22744591, 0.82790066, 0.48361515, 0.6680354 ,
       0.89521828, 0.47225207, 0.28213312, 0.92231817, 0.62405657,
       0.5494585 , 0.21975445, 0.20543886, 0.0473631 , 0.35145478,
       0.88440475, 0.87470945, 0.04396673, 0.77179737, 0.38016007])

In [8]:
np.random.randn(25)

array([ 0.23309985,  0.38770906, -0.92358573, -0.3577495 , -1.28169984,
        2.27747211,  0.21363805,  0.56053763,  0.63242225,  0.67958287,
        1.11350461, -1.42849842,  1.36816653,  0.25136559, -0.21147669,
        0.34810851, -1.79960548, -0.22440962, -1.61303304,  0.97807541,
       -0.75139662,  0.5547667 ,  0.51935221,  2.6720759 , -1.25082436])