In [7]:
import numpy as np


In [8]:
a = np.array([8,6,5])
a

array([8, 6, 5])

In [10]:
a1 = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
a2 = np.array([[4,8,7],[3,1,5],[6,9,13]])
a2.shape

(3, 3)

In [11]:
b = np.array([[6,7,8],[2,3,4]])
b

array([[6, 7, 8],
       [2, 3, 4]])

In [12]:
b.shape

(2, 3)

In [15]:
a1 = np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])
a2 = np.array([[[4,47],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
a2

array([[[  4,  47],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [16]:
a2.shape

(3, 3, 2)

In [17]:
a1[1,0]

9

In [18]:
a1[1,0:3:1] ## for row 

array([9, 3, 5])

In [19]:
a1[1][0]

9

In [ ]:
## subscripting  ## slicing me out of bound bhi le sakte hai
# a1[ , , ]

In [20]:
a1[0:3:1,1]  ## for column

array([ 8,  3, 15])

In [22]:
a1[0,-1:]

array([4])

In [23]:
a1[2:3]

array([[11, 15, 17]])

In [24]:
a1[2:]

array([[11, 15, 17],
       [19, 31,  8]])

In [25]:
a1[-1:]

array([[19, 31,  8]])

In [26]:
a1[1,-1:]

array([5])

In [27]:
a1[1,2:3]

array([5])

In [28]:
a1[1,2:]

array([5])

In [21]:
a1[0:5:1,2].shape

(4,)

In [32]:
a2[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [33]:
a2

array([[[  4,  47],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [35]:
a1+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [36]:
a1[0,:] = [30,40,50]

In [37]:
a1

array([[30, 40, 50],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [39]:
a1[:,1]= [10, 20 ,30,40]

In [40]:
a1

array([[30, 10, 50],
       [ 9, 20,  5],
       [11, 30, 17],
       [19, 40,  8]])

In [46]:
a1[:2,1:] = [[202,303],[404,505]]
a1

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11,  30,  17],
       [ 19,  40,   8]])

In [47]:
np.append(a1,[[1,1,1]],axis = 0) # Zero to add row-wise

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11,  30,  17],
       [ 19,  40,   8],
       [  1,   1,   1]])

In [51]:
np.append(a1,[[1],[1],[1],[1]],axis = 1)


array([[ 30, 202, 303,   1],
       [  9, 404, 505,   1],
       [ 11,  30,  17,   1],
       [ 19,  40,   8,   1]])

In [52]:
np.delete(a1,1,1)

array([[ 30, 303],
       [  9, 505],
       [ 11,  17],
       [ 19,   8]])

In [53]:
np.delete(a1,3,axis=0)

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11,  30,  17]])

In [54]:
a1.size

12

In [55]:
a1.reshape(6,2)

array([[ 30, 202],
       [303,   9],
       [404, 505],
       [ 11,  30],
       [ 17,  19],
       [ 40,   8]])

In [57]:
a1.dtype

dtype('int32')

In [59]:
a1.astype('uint16')

array([[ 30, 202, 303],
       [  9, 404, 505],
       [ 11,  30,  17],
       [ 19,  40,   8]], dtype=uint16)

In [60]:
d = np.array([3.5,3,7.])
d

array([3.5, 3. , 7. ])

In [61]:
d.dtype

dtype('float64')

In [62]:
d.astype('uint16')

array([3, 3, 7], dtype=uint16)

In [63]:
a1.mean(axis=1)

array([178.33333333, 306.        ,  19.33333333,  22.33333333])

In [64]:
a1.std(axis=1)

array([112.70117815, 214.02024826,   7.9302515 ,  13.27487183])

In [66]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [69]:
np.random.randint(1,15,[3,4])

array([[ 5,  5,  5,  8],
       [ 6,  8, 13,  5],
       [11, 10,  3, 12]])

In [ ]:
#nutshell
## we create arrays
## 1. np.array()
## 2. np.ones()
## 3. np.zeros()
## 4. np.random.randint()
## np.arange()